# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The cloudbau blog
email: j.klare@cloudbau.de
description: > # this means to ignore newlines until "baseurl:"
  This is the official cloudbau blog and it`s articles are mainly about
  OpenStack, Automation and all the related topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cloudbau.github.io" # the base hostname & protocol for your site
twitter_username: cloudbau_de
github_username:  cloudbau

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
